source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'AlamofireRSSParser_Example' do
  pod 'AlamofireRSSParser', :path => '../'
end

target 'AlamofireRSSParser_Tests' do
  pod 'AlamofireRSSParser', :path => '../'  
end
